# this file specifies the dependencies between your SQL objects
#
#
# Example of default load orders:
# Friend:
# TeamMember:
# TeamMate:
#
# Specifying the above, with no children SQL objects
#   will load your objects in the default order
#   specified per each database type.  Some databases
#   support certain objects that others don't.
#
# These default load orders can be found in the following
#   configuration folders: ( ????? )
#
# Examples of more complicated load orders:
# Friend:
#   view_friends:
#     rule_view_friends_delete:
#     rule_view_friends_insert:
# TeamMember:
# TeamMate:
#   view_team_mates:
#   rule_view_team_members_delete:
#
#
# Right now this file is just in brainstorming mode
#   And i'm trying to figure out the best interface
#   for various users' needs
#
# Unaccounted for:
#   - multiple databases
#   - NoSQL (maybe)
#   - more complicated load orders
#   - conditional load orders (GTFO!)

