language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-19mode
#  - jruby
services:
 - mysql
 - postgresql
before_script:
  - cp spec/config/database.yml.travis spec/config/database.yml
  - mysql -e "create user 'skiima'@'localhost'"
  - rake skiima:setup:db:postgresql
  - rake skiima:setup:db:mysql
#script: rake
