---
production:
  adapter: postgresql
  encoding: utf8
  database: skiima_production
  username: skiima
  password: test

development:
  adapter: postgresql
  encoding: utf8
  database: skiima_development
  username: skiima
  password: test

test:
  adapter: postgresql
  encoding: utf8
  database: skiima_test
  username: skiima
  password: test

postgresql_test:
  adapter: postgresql
  encoding: utf8
  database: postgresql_test
  username: skiima
  password: test

mysql_test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mysql_test
  pool: 5
  username: skiima
  password: test
  socket: /tmp/mysql.sock

mysql2_test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mysql2_test
  pool: 5
  username: skiima
  password: test
  socket: /tmp/mysql.sock

sqlserver_test:
  adapter: sqlserver
  encoding: utf8
  database: skiima_test
  username: skiima
  password: test

